aspect-build/rules_jest

- jest/private/v28.1.1/pnpm-lock.yaml
- jest/private/v28.1.2/pnpm-lock.yaml
- jest/private/v29.0.0/pnpm-lock.yaml
- jest/private/v29.0.1/pnpm-lock.yaml
- jest/private/v29.0.2/pnpm-lock.yaml
- jest/private/v29.0.3/pnpm-lock.yaml
- jest/private/v29.1.0/pnpm-lock.yaml
- jest/private/v29.1.1/pnpm-lock.yaml
- jest/private/v29.1.2/pnpm-lock.yaml
- jest/private/v29.2.0/pnpm-lock.yaml
- jest/private/v29.2.1/pnpm-lock.yaml
- jest/private/v29.2.2/pnpm-lock.yaml
- jest/private/v29.3.0/pnpm-lock.yaml
- jest/private/v29.3.1/pnpm-lock.yaml
- jest/private/versions.bzl
Resolves https://github.com/aspect-build/rules_jest/issues/64
"+31,488 −0" 😂  Do I get a GitHub achievement for this one?
> chore: add jest versions v28.1.1 through v29.3.1

- example/custom_sequencer/index.test.js
- example/custom_sequencer/index_2.test.js
- example/esm/BUILD.bazel
- example/esm/index.mjs
- example/esm/index.test.mjs
- example/esm/jest.config.mjs
- example/esm_type_module/BUILD.bazel
- example/esm_type_module/index.js
- example/esm_type_module/index.test.js
- example/esm_type_module/jest.config.mjs
- example/esm_type_module/package.json
- example/sharding/index.test.js
- example/sharding/index_2.test.js
- example/simple/index.test.js
Resolves https://github.com/aspect-build/rules_jest/issues/65
> chore: add examples of using esm with jest_test both .mjs files and with 'type':'module' in package.json

- example/custom_snapshot_resolver/BUILD.bazel
- example/custom_snapshot_resolver_files/BUILD.bazel
- example/simple/BUILD.bazel
- example/snapshots/BUILD.bazel
- example/snapshots_files/BUILD.bazel
- jest/defs.bzl
- jest/dependencies.bzl
Depends on https://github.com/aspect-build/rules_js/pull/759
> fix: ensure all jest targets are marked testonly

- jest/private/jest_test.bzl
- jest/tests/BUILD.bazel
Added logic to invert the chdir argument and adapt paths passed as cli options to the jest command
> Fixes #89 Added support for setting the chdir attr

- BUILD.bazel
- jest/tests/BUILD.bazel
- jest/tests/case8.test.js
- test_case8.jest.config.js
Mainly to demo + test https://github.com/aspect-build/rules_jest/issues/86
> test: add test with jest config in parent directory

- jest/defs.bzl
Also pass data to the tool for jest snapshot updates incase there are load bearing data deps the config requires.
How has this been tested?
> fix: also pass data to js_binary tool for jest snapshot updates

- e2e/case6.sh
- jest/private/jest_config_template.mjs
- jest/private/jest_test.bzl
fixes #124
**Type of change**
**Test plan**
> fix: enable coverage with COVERAGE_DIR env

- e2e/update_snapshots_test.sh
- example/BUILD.bazel
- jest/defs.bzl
- jest/private/bazel_snapshot_reporter.cjs
- jest/private/bazel_snapshot_resolver.cjs
- jest/private/jest_config_template.mjs
- jest/private/jest_test.bzl
- jest/tests/BUILD.bazel
- jest/tests/case10/case10.jest.config.js
- Bug fix (change which fixes an issue)
- Refactor (a code change that neither fixes a bug or adds a new feature)
- Breaking change (this change will force users to change their own code or config)
- Relevant documentation has been updated
- Manual testing; please provide instructions so we can reproduce:
> feat: run snapshot updates as tests

- .aspect/workflows/terraform/workflows.tf
> chore: update to Aspect Workflows 5.7.0-rc10

- docs/troubleshooting.md
Common troubleshooting tips that I recall atm. I'm sure there's more that I'll try to add when I come across/remember them...
- Documentation (updates to documentation or READMEs)
> docs: add troubleshooting guide

- .aspect/workflows/.bazelrc
- .aspect/workflows/config.yaml
- bazelrc
Makes a much cleaner example for the docsite this way.
---
> chore: set Workflows flags in .aspect/workflows/terraform/.bazelrc file

- .aspect/workflows/config.yaml
- BUILD.bazel
- MODULE.bazel
- e2e/smoke/MODULE.bazel
- jest/BUILD.bazel
- jest/private/BUILD.bazel
Rolling out gazelle checks to all our open source repos on Aspect Workflows.
Test run with fixup annotations: https://buildkite.com/aspect-build/rules-jest/builds/110
---
> chore: add gazelle task to Aspect Workflows config

- .aspect/workflows/terraform/workflows.tf
Set new scale_out_factor to 3 to cover all Workflows tasks created per job
> chore: upgrade to Aspect Workflows 5.8.2

- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
Similar to https://github.com/aspect-build/rules_js/pull/1392 and https://github.com/aspect-build/rules_jasmine/pull/102
> chore: run Aspect Workflows setup step on small instances

- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
- docs/BUILD.bazel
- docs/delivery.sh
Tested here https://buildkite.com/aspect-build/rules-jest/builds/199
> chore: enable workflows delivery on demostration target

- .aspect/cli/config.yaml
- .aspect/workflows/bazelrc
- .aspect/workflows/config.yaml
- .aspect/workflows/terraform/workflows.tf
- .bazeliskrc
- .bazelversion
> chore: upgrade to Aspect Workflows 5.9.0-rc.9

- .aspect/workflows/config.yaml
- Manual testing; please provide instructions so we can reproduce:
See if we get comments posted to PRs here
> chore: enable workflows updates in code review thread

- .github/workflows/release_prep.sh
> docs: bzlmod install instructions

- e2e/smoke/MODULE.bazel
> test: remove unnecessary aspect_bazel_lib dep in e2e/smoke

- README.md
- troubleshooting.md
- Documentation (updates to documentation or READMEs)
> docs: adding troubleshooting.md for common challenges

- jest/private/jest_test.bzl
- jest/tests/env_inherit/BUILD.bazel
- jest/tests/env_inherit/env_inherit.test.js
to jest_tests
- New feature or functionality (change which adds functionality)
- Relevant documentation has been updated
- Suggested release notes are provided below: Partly improves https://github.com/aspect-build/rules_js/issues/1313
- New test cases added
> feat(env_inherit): add ability to pass env variables from system

- MODULE.bazel
- e2e/npm_packages/MODULE.bazel
- e2e/smoke/MODULE.bazel
- e2e/swc/MODULE.bazel
- e2e/swc/WORKSPACE.bazel
- jest/dependencies.bzl
> build: upgrade to rules_js v2

- .bcr/config.yml
- .bcr/metadata.template.json
> chore: update bcr maintainer info
