e2e/case6.sh, e2e/case7.sh, jest/private/BUILD.bazel, jest/private/jest_config_template.mjs, jest/private/jest_test.bzl, jest/private/noop.sh, jest/tests/BUILD.bazel, jest/tests/case6.index.js, jest/tests/case6.test.js, jest/tests/case7.index.js, jest/tests/case7.test.js
https://github.com/aspect-build/rules_jest/issues/34
First time doing anything coverage-related in Bazel, so I may be doing something weird.
=> feat: jest coverage output

example/BUILD.bazel, example/snapshots/BUILD.bazel, jest/defs.bzl
It should be available to any downstream aggregate `write_source_files` targets.
From Bazel slack thread: https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1674589705258479?thread_ts=1674589681.819949&cid=CEZUUKQ6P
=> fix: make snapshot write_source_files update target public visibility

docs/rules.md, example/simple/BUILD.bazel, example/simple/index.test.js, example/snapshots/BUILD.bazel, jest/defs.bzl
Fixes #95
BREAKING CHANGE:
The default timeout for jest_test is now short (1m by default) rather than moderate (5m by default).
Tests that take more than 1m should have a size or timeout attribute added.
=> fix: timeout/size shouldn't be passed to js_binary 

example/snapshots/BUILD.bazel, jest/defs.bzl
Missed these in #110
Maybe we should have a helper in bazel-lib similar to `propagate_well_known_tags` ?
=> fix: remove other attributes that don't belong on js_binary

jest/defs.bzl
We over-filtered this list.
How has this been tested?
=> fix: env is valid for js_test, js_binary and js_run_binary

jest/defs.bzl
rules_js js_test base attributes that jest_test uses requires setting `unresolved_symlinks_enabled` to True based on the `@aspect_rules_js//js/private:experimental_allow_unresolved_symlinks` condition to enable the optimized Bazel 6 patches only when the user is using Bazel 6 **AND** unresolved symlinks are enabled. They are enabled by default but they can be disabled by the user so we need to check anyway.
**Type of change**
For WORKSPACE users that are pinning `aspect_rules_js`, this bumps the minimum rules_js version required for rules_jest compatibility to 1.24.0. WORKSPACE that get the version of rules_js transitively from `rules_jest_dependencies` are not affected. bzlmod users are also not affected since bzlmod ensure the minimum version of …
=> perf: use rules_js Bazel 6 optimized fs patches if using Bazel 6 and experimental_allow_unresolved_symlinks is on

.bazelversion, README.md, jest/defs.bzl, jest/private/jest_test.bzl
Makes the macro less leaky abstraction, since bazel query still shows a jest_test.
**Type of change**
Refactor (a code change that neither fixes a bug or adds a new feature)
**Test plan**
How has this been tested?
Covered by existing test cases
=> fix: jest_test rule named the same as the macro

jest/private/jest_config_template.mjs, jest/tests/BUILD.bazel, jest/tests/case11/case11.index.js, jest/tests/case11/case11.test.js, jest/tests/case11/case11a.jest.config.js, jest/tests/case11/case11b.jest.config.js
fixes #126 
**Type of change**
**Test plan**
How has this been tested?
If part of the test plan included manual testing, please provide instructions so we can reproduce.
Please also list any relevant details for your test configuration.
=> fix: support jest config function

e2e/smoke/.bazeliskrc
=> chore: remove bazeliskrc from e2e

MODULE.bazel, e2e/npm_packages/MODULE.bazel, e2e/smoke/MODULE.bazel, jest/dependencies.bzl, jest/tests/BUILD.bazel, jest/tests/case10.jest.config.js, jest/tests/case10.setup.js, jest/tests/case10.test.js, jest/tests/case10/__snapshots__/case10.test.js.snap, jest/tests/case10/case10.config-init.js, jest/tests/case10/case10.jest.config.js, jest/tests/case10/case10.setup.js, jest/tests/case10/case10.test.js, jest/tests/package.json, pnpm-lock.yaml
See https://github.com/aspect-build/rules_jest/issues/128
=> test: add js_library config tests

e2e/smoke/.bazelrc
Windows bzlmod presubmit doesn't like bazelrc files via symlinks.
See https://github.com/bazelbuild/bazel-central-registry/pull/662 for failure.
---
=> chore: fix bzlmod windows presubmit

.bcr/presubmit.yml, MODULE.bazel, e2e/npm_packages/MODULE.bazel, e2e/smoke/MODULE.bazel, jest/dependencies.bzl
Windows fix. BCR should be green now for Windows with this change.
---
=> chore: bump rules_js dep to 1.29.2 to pickup Windows fix

.bazelrc, .github/workflows/ci.yaml, e2e/smoke/BUILD.bazel, jest/private/jest_config_template.mjs
Limiting Windows CI to just e2e/smoke which is tested by the BCR pre-submit since jest on Windows does not auto-discover tests due to the old symlinks issue. The upstream fix to enable symlinks in jest-haste-map appears to not have worked on Windows.
---
- Bug fix (change which fixes an issue)
=> fix: windows file URL issue

.github/workflows/ci.yaml, e2e/smoke/MODULE.bazel
`exclude` added in v3: https://github.com/bazel-contrib/.github/commit/f4ef92734cbf2580f7ef53df92aa0281a4d82220
=> chore: bump CI workflows template to v3 which has the exclude attribute

.aspect/workflows/terraform/workflows.tf
Haven't created the warming pipeline yet for this deployment but when I do the Buildkite queue in the Buildkite cluster will be named `warming`
=> chore: fix warming queue name in Aspect Workflows terraform

example/(simple_group)/BUILD.bazel, example/(simple_group)/index.js, example/(simple_group)/index.test.js, example/(simple_group)/jest.config.cjs, example/(simple_group)/jest.config.js, example/(simple_group)/jest.config.json, example/(simple_group)/jest.config.mjs, jest/private/jest_test.bzl
I can't tell if this is actually a good fix, let me know!
- Bug fix (change which fixes an issue): https://github.com/aspect-build/rules_jest/issues/151
- New test cases added: I copied the `simple/` folder to `(simple_group)/` to ensure all the different types of configs pass.
=> Add quotes around config path

.aspect/workflows/bazelrc, .aspect/workflows/terraform/.terraform.lock.hcl, .aspect/workflows/terraform/main.tf, .aspect/workflows/terraform/workflows.tf, .pre-commit-config.yaml
Also
- updated versions of pre-commit hooks
- fix remote_download_minimal bazelrc flags `common` issue (related to https://github.com/bazelbuild/bazel/pull/20720)
=> chore: upgrade to Aspect Workflows 5.9.0-rc.10

e2e/case13.sh, jest/private/jest_config_template.mjs, jest/tests/BUILD.bazel, jest/tests/case13.jest.config.js, jest/tests/case13.test.js
See https://github.com/aspect-build/rules_jest/issues/230
---
- New feature or functionality (change which adds functionality)
- Suggested release notes are provided below:
Now cacheDirector is set to TEST_TMPDIR by default to improve test isolation and cleanup. 
- This change is foundational and affects every test in the codebase. Existing tests confirm this doesn't introduce a regression.
- It doesn't appear to be possible to determine the cacheDirectory from within a jest test suite. However, an e2e test is added that explicitly sets --test_tmpdir and confirms that jest produced outputs in that folder indicating that it was successfully passed through the config chain.
- The case where user configuration specifies cacheDirectory via config is …
=> feat: default cacheDirectory to TEST_TMPDIR

.aspect/workflows/bazelrc
This test has only been green because the remote cache has been masking the underlying failure due to https://github.com/bazelbuild/bazel/issues/20577. The failure is specific `--nobuild_runfile_links` with coverage enabled which is currently only on Aspect Workflows CI. This PR comments out `--nobuild_runfile_links` for now until the issue is resolved.
=> chore: green up //jest/tests/fixed_args:fixed_args_test on CI

.aspect/workflows/config.yaml
An example of making a `bazel query //...` call in the before_task hook so the build asserts that invariant is green.
Some minimal flags are required:
startup flags:
- `--nohome_rc` (ignore any `~/.bazelrc` incase one gets created on the runner unintentionally by a rogue job; this flag could we could set in `/etc/bazel.bazelrc` in the future)
- `--bazelrc=.aspect/workflows/bazelrc` (if this file exists, which it does in this repo, this keeps the bazel flags on the `bazel query` call consistent with what Workflows uses for `bazel test`)
regular flags:
- `--aspect:lock_version` (ensure the version of the Aspect CLI used matches the Workflows version and the one used in bazel test incase there happens to be another version configured in `.bazeliskrc`)
- `--config=workflows` (picks up all the …
=> chore: add example of using Aspect Workflows task hooks

jest/defs.bzl
Currently everyone gets this target even if `snapshots` was left empty. This causes extra execution for folks who use CI to run all changed targets. It's preferable not to have a duplicate target like this.
---
- Bug fix (change which fixes an issue)
- Relevant documentation already implies this change
- Suggested release notes are provided below:
Only generate `*_update_snapshots` targets upon request
=> snapshots: only create `*_update_snapshots` target upon request

.aspect/workflows/config.yaml
Example of dumping memory usage and detailed PID info of the bazel server in an after_task hook
=> chore: track bazel server memory usage after test task

.aspect/cli/config.yaml, docs/BUILD.bazel, e2e/update_snapshots_test.sh, example/multiple_snapshots/BUILD.bazel, example/snapshots/BUILD.bazel, jest/tests/BUILD.bazel, jest/tests/case10/BUILD.bazel, jest/tests/case10a/BUILD.bazel, jest/tests/case10a/__snapshots__/case10a.test.js.snap, jest/tests/case10a/case10a.config-init.js, jest/tests/case10a/case10a.jest.config.js, jest/tests/case10a/case10a.setup.js, jest/tests/case10a/case10a.test.js, jest/tests/package_json_module/BUILD.bazel
Pre-factor from https://github.com/aspect-build/rules_jest/pull/269.
Fixes build issue:
```
(17:42:17) ERROR: One of the output paths 'bazel-out/k8-fastbuild/bin/jest/tests/case10' (belonging to //jest/tests:case10) and 'bazel-out/k8-fastbuild/bin/jest/tests/case10/case10.test.js' (belonging to //jest/tests:case10_update_snapshots) is a prefix of the other. These actions cannot be simultaneously present; please rename one of the output files or build just one of them
(17:42:17) ERROR: One of the output paths 'bazel-out/k8-fastbuild/bin/jest/tests/case10' (belonging to //jest/tests:case10) and 'bazel-out/k8-fastbuild/bin/jest/tests/case10/__snapshots__/case10.test.js.snap' (belonging to //jest/tests:case10a) is a prefix of the other. These actions cannot be simultaneously present; please …
```
=> fix: refactor case10 and case10a tests so they don't have duplicate outputs

MODULE.bazel, e2e/npm_packages/MODULE.bazel, e2e/smoke/MODULE.bazel, e2e/swc/MODULE.bazel, jest/dependencies.bzl
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
=> chore: bump miminum dep to aspect_bazel_lib 2.7.6

MODULE.bazel, e2e/npm_packages/MODULE.bazel, e2e/smoke/MODULE.bazel, e2e/swc/MODULE.bazel, jest/dependencies.bzl
aspect_bazel_lib min bump goes along with rules_js bump in https://github.com/aspect-build/rules_js/pull/1763 to pick up fix for copy_to_directory that affects npm_package: https://github.com/aspect-build/bazel-lib/pull/857.
=> chore: bump to rules_js 2.0.0-rc1 and minimum aspect_bazel_lib 2.7.7

MODULE.bazel, jest/dependencies.bzl
Ensures users pick up https://github.com/bazelbuild/rules_nodejs/pull/3760 fix which is a footgun that should be avoided.
=> chore: bump minimum rules_nodejs to 6.2.0

docs/troubleshooting.md, jest/private/jest_config_template.mjs
Use of this Jest feature essentially bypasses all our configuration in`jest_config_template.mjs` breaking things like snapshots, [performance](https://github.com/aspect-build/rules_jest/pull/301), coverage, bazel sharding etc.
Ref #291
---
- Searched for relevant documentation and updated as needed: yes
- Breaking change (forces users to change their own code or config): no
- Suggested release notes appear below: yes
Log warnings when incompatible jest config is used.
- Manual testing; run jest with `config.projects`
=> feat: warn when incompatible jest config is used

jest/defs.bzl, jest/private/BUILD.bazel, jest/private/bazel_haste_map.cjs, jest/private/jest_config_template.mjs, jest/private/jest_test.bzl
Create a custom `HasteMap` implementation that uses a file list provided by the `jest_test` rule instead of re-traversing the fs or depending on `watchman` or `find`.
This custom `HasteMap` extends the default from `jest-haste-map` while overriding some methods to remove the fs traversal as well as removing caching functionality that is not applicable with rules_jest.
Ref #50
---
- Searched for relevant documentation and updated as needed: yes
- Breaking change (forces users to change their own code or config): no
- Suggested release notes appear below: yes
Use a custom Jest haste-map implementation to reuse information calculated by the `jest_test` rule instead of recomputing within Jest.
- Manual testing; run on a large repo such as [suggested in …
=> perf: replace jest fs traversal with bazel defined filelist

jest/private/bazel_haste_map.cjs, jest/private/jest_config_template.mjs
Use an env var instead of global so any child processes that jest launches will have access.
---
- Manual testing; run on a large repo when `run_in_band = False`
=> fix: use of the bazel supplied list of runfiles by jest subprocesses

README.md, docs/troubleshooting.md, e2e/swc/README.md
=> chore: mention @swc/jest specifically

jest/private/jest_config_template.mjs, jest/private/jest_test.bzl
Attempts to solve https://github.com/aspect-build/rules_jest/pull/294 through a rule attribute instead of an ENV variable
This allows us to upstream the pattern we use internally in a way others can use. We have ejected from the main reporting mechanism and built in our own because of our needs.
=> Add `auto_configure_reporting` attribute to allow end users to eject from default behavior
